# Generated by Django 3.0.4 on 2020-03-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200317_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='goods/images/', verbose_name='封面图'),
        ),
    ]
