# Generated by Django 3.0.4 on 2020-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200320_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='icon',
            field=models.ImageField(default='', help_text='分类图标', upload_to='category/icons/', verbose_name='分类图标'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(default='', help_text='分类封面图', upload_to='category/images/', verbose_name='分类封面图'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别'),
        ),
    ]
