# Generated by Django 3.0.4 on 2020-03-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20200321_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='课程类型id', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.CourseCategory', verbose_name='课程类别'),
        ),
    ]
