# Generated by Django 3.0.4 on 2020-03-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20200322_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='index',
            field=models.IntegerField(default=0, help_text='显示顺序', verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='课程id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='goods.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(help_text='章节id', on_delete=django.db.models.deletion.CASCADE, related_name='video', to='goods.Lesson', verbose_name='章节'),
        ),
    ]
