# Generated by Django 3.0.4 on 2020-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20200325_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='good/videos/%Y/%m/%d/', verbose_name=''),
        ),
    ]
