# Generated by Django 3.0.4 on 2020-04-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20200427_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='goods/videos/%Y/%m/%d/', verbose_name=''),
        ),
    ]
