# Generated by Django 3.0.4 on 2020-04-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20200427_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='goods/videos/', verbose_name=''),
        ),
    ]
