# Generated by Django 3.0.4 on 2020-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20200427_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vod_id',
            field=models.IntegerField(null=True, verbose_name='vod_id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='goods/videos/%Y/%m/%d/', verbose_name='视频文件'),
        ),
    ]
