# Generated by Django 3.0.4 on 2020-04-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20200427_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vod_id',
            field=models.CharField(max_length=100, null=True, verbose_name='vod_id'),
        ),
    ]
