# Generated by Django 3.0.4 on 2020-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20200427_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='icon',
            field=models.ImageField(help_text='分类图标', null=True, upload_to='category/icons/', verbose_name='分类图标'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(help_text='分类封面图', null=True, upload_to='category/images/', verbose_name='分类封面图'),
        ),
    ]
