# Generated by Django 3.0.4 on 2020-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_auto_20200428_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='视频地址', null=True, verbose_name='访问地址'),
        ),
    ]
