# Generated by Django 3.0.4 on 2020-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20200320_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('paying', '待支付')], default='paying', help_text='订单状态', max_length=30, verbose_name='订单状态'),
        ),
    ]
