# Generated by Django 2.2.11 on 2020-03-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20200322_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordergoods', to='trade.OrderInfo', verbose_name='订单信息'),
        ),
    ]
