# Generated by Django 3.0.4 on 2020-03-26 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0006_auto_20200325_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='marketing_code',
            field=models.ForeignKey(blank=True, help_text='推广码', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.MarketingCode', verbose_name='推广码'),
        ),
        migrations.CreateModel(
            name='TeacherManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField(default=0.0, help_text='佣金金额', verbose_name='佣金金额')),
                ('scale_factor', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '老师佣金',
                'verbose_name_plural': '老师佣金',
            },
        ),
    ]
