# Generated by Django 2.2.11 on 2020-03-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20200327_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherManagement',
        ),
    ]
