# Generated by Django 2.2.11 on 2020-03-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0010_delete_teachermanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField(default=0.0, help_text='佣金金额', verbose_name='佣金金额')),
                ('scale_factor', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_commission', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '老师佣金',
                'verbose_name': '老师佣金',
            },
        ),
    ]
