# Generated by Django 2.2.11 on 2020-03-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_teachermanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='marketing_code',
        ),
    ]
