# Generated by Django 2.2.11 on 2020-03-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_remove_orderinfo_marketing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='marketing_code',
            field=models.CharField(blank=True, help_text='营销推广码', max_length=30, null=True, unique=True, verbose_name='营销推广码'),
        ),
    ]
