# Generated by Django 3.0.4 on 2020-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20200327_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermanagement',
            name='total_commission',
            field=models.FloatField(default=0.0, help_text='历史总佣金', verbose_name='历史总佣金'),
        ),
    ]
