# Generated by Django 3.0.4 on 2020-03-28 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_teachermanagement_total_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermanagement',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='增加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermanagement',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
