# Generated by Django 3.0.4 on 2020-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_auto_20200328_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermanagement',
            name='scale_factor',
            field=models.FloatField(default=0.0, help_text='佣金系数', verbose_name='佣金系数'),
        ),
    ]
