# Generated by Django 2.2.11 on 2020-04-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_auto_20200328_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='buy_it',
            field=models.BooleanField(default=True, help_text='是否购买', verbose_name='是否购买'),
        ),
    ]
