# Generated by Django 3.0.4 on 2020-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_shoppingcart_buy_it'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_mobile',
            new_name='signer_mobile',
        ),
    ]
