# Generated by Django 3.0.4 on 2020-04-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_auto_20200407_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='confirm',
            field=models.CharField(choices=[('WAITING_LEARN', '未学习'), ('LEARNED', '已学习'), ('CANCELED', '已取消'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='WAITING_LEARN', help_text='核销', max_length=30, verbose_name='核销'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', help_text='订单状态', max_length=30, verbose_name='订单状态'),
        ),
    ]
