# Generated by Django 3.0.4 on 2020-04-29 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0020_auto_20200428_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermanagement',
            name='user',
            field=models.OneToOneField(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_commission', to=settings.AUTH_USER_MODEL, verbose_name='课程教师'),
        ),
    ]
