# Generated by Django 3.0.4 on 2020-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_auto_20200429_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='confirm',
            field=models.CharField(choices=[('WAITING_LEARN', '未学习'), ('LEARNED', '已学习'), ('CANCELED', '已取消')], default='WAITING_LEARN', help_text='核销', max_length=30, verbose_name='核销'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
    ]
