"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
# 将apps作为环境导入
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0+5-f$&c$$s02ziev6^2h2eq%hj+^=ud=fnk5=_-^6xijne6q3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = 'users.UserProfile'
# Application definition

INSTALLED_APPS = [
    'extra_apps.simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users.apps.UsersConfig',
    'apps.goods.apps.GoodsConfig',
    'apps.trade.apps.TradeConfig',
    'apps.user_operation.apps.UserOperationConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'rest_framework.authtoken',
    'social_django',
    'apps.marketing.apps.MarketingConfig',
    'import_export',
]
CORS_ORIGIN_ALLOW_ALL = True
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'store',  # Or path to database file if using sqlite3.
        'USER': 'root',  # Not used with sqlite3.
        'PASSWORD': 'admin',  # Not used with sqlite3.
        'HOST': 'localhost',  # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '3306',  # Set to empty string for default. Not used with sqlite3.
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.BasicAuthentication',
                                       #'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
                                       'rest_framework.authentication.SessionAuthentication',],
    'DEFAULT_RENDERER_CLASSES': [
        'utils.render.EmberJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    }

}

ADMIN_LIST_PER_PAGE = 40
#DRF拓展
REST_FRAMEWORK_EXTENSIONS = {
    # 缓存时间
    'DEFAULT_CACHE_RESPONSE_TIMEOUT':60,
    # 缓存存储
    'DEFAULT_USE_CACHE':'default',
}

AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
    'social_core.backends.weixin.WeixinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}
# simpleui
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_ANALYSIS = False
# 指定simpleui默认的主题,指定一个文件名，相对路径就从simpleui的theme目录读取
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menu_display': ['营销管理', '商品管理','交易管理', '用户操作管理','用户管理'],
    'menus':[{
        'app': 'trade',
        'name': '交易管理',
        'icon': 'far fa-file',
        'models': [{
            'name': '订单信息',
            'icon': 'icon fas fa-shopping-bag',
            'url': 'trade/orderinfo/'
        },{
            'name': '订单商品',
            'icon': 'icon fas fa-shopping-bag',
            'url': 'trade/ordergoods/'
        },{
            'name': '购物车',
            'icon': 'icon fas fa-shopping-cart',
            'url': 'trade/shoppingcart/'
        },]
    },{
        'app': 'marketing',
        'name': '用户操作管理',
        'icon': 'fas fa-user',
        'models': [{
            'name': '用户地址',
            'icon': 'icon fas fa-truck',
            'url': 'user_operation/useraddress/'
        },{
            'name': '用户咨询',
            'icon': 'icon far fa-user',
            'url': 'user_operation/userask/'
        },{
            'name': '用户消息',
            'icon': 'icon far fa-user',
            'url': 'user_operation/usermessage/'
        },{
            'name': '用户留言',
            'icon': 'icon far fa-user',
            'url': 'user_operation/userleavingmessage/'
        },{
            'name': '用户课程',
            'icon': 'icon far fa-user',
            'url': 'user_operation/usercourse/'
        },{
            'name': '用户收藏',
            'icon': 'far fa-user',
            'url': 'user_operation/userfav/'
        },{
            'name': '用户评论',
            'icon': 'fas fa-book',
            'url': 'user_operation/coursecomments/'
        }]
    },{
        'app': 'marketing',
        'name': '营销管理',
        'icon': 'icon far fa-file',
        'models': [{
            'name': '营销关系',
            'icon': 'fa fa-user',
            'url': 'marketing/marketingrelationship/'
        },{
            'name': '营销海报',
            'icon': 'fa fa-user',
            'url': 'marketing/poster/'
        },{
            'name': '营销推广码',
            'icon': 'fa fa-user',
            'url': 'marketing/marketingcode/'
        },{
            'name': '营销系数配置',
            'icon': 'far fa-file',
            'url': 'marketing/marketerconfigs/'
        },]
    },{
        'app': 'goods',
        'name': '商品管理',
        'icon': 'fas fa-shopping-cart',
        'models': [{
            'name': '课程类别',
            'icon': 'icon fas fa-book',
            'url': 'goods/coursecategory/'
        },{
            'name': '课程信息',
            'icon': 'icon fas fa-book',
            'url': 'goods/course/'
        },{
            'name': '课程章节',
            'icon': 'icon fas fa-book',
            'url': 'goods/lesson/'
        },{
            'name': '课程视频',
            'icon': 'icon fas fa-film',
            'url': 'goods/video/'
        },{
            'name': '课程资源',
            'icon': 'icon fas fa-book',
            'url': 'goods/courseresource/'
        },{
            'name': '轮播课程',
            'icon': 'fas fa-ad',
            'url': 'goods/banner/'
        }]
    },{
        'app': 'users',
        'name': '用户管理',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': 'users/userprofile/'
        },{
            'name': '营销人员申请',
            'icon': 'icon far fa-file',
            'url': 'marketing/marketerapplication/'
        },{
            'name': '导师身份申请',
            'icon': 'icon far fa-file',
            'url': 'marketing/teacherapplication/'
        },{
            'name': '教师佣金记录',
            'icon': 'icon far fa-file',
            'url': 'trade/teachermanagement/'
        },{
            'name': '组',
            'icon': 'fas fa-users-cog',
            'url': 'auth/group/'
        },{
            'name': '短信验证码',
            'icon': 'icon far fa-comment-dots',
            'url': 'users/verifycode/'
        }]
    },]
}
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_URL = "/media/"
#STATICFILES_DIRS = (
#    os.path.join(BASE_DIR, 'staticfiles'),
#)


MEDIA_ROOT = os.path.join(BASE_DIR, "media")
CKEDITOR_UPLOAD_PATH = 'ckeditor_uploads/'

import datetime

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}
# 手机号码正则表达式
REGEX_MOBILE = "^(13[0-9]|14[5-9]|15[0-3,5-9]|16[2,5,6,7]|17[0-8]|18[0-9]|19[0-3,5-9])\\d{8}"

# 云片网设置
APIKEY = "79c7af6a0e03809ac9a2ca74b6363167"
APP_ID = 'wx09a82df3fbf9d3a9'
APP_SECRET = 'a9bf876aaa883cf9af111eeb513eb029'
SOCIAL_AUTH_WEIXIN_KEY = 'wx09a82df3fbf9d3a9'
SOCIAL_AUTH_WEIXIN_SECRET = 'a9bf876aaa883cf9af111eeb513eb029'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/index/'

ALI_APP_ID = "2016101800713621"
ALI_PUB_KEY_PATH = os.path.join(BASE_DIR,'apps/trade/keys/alipay_key.txt')
PRIVATE_KEY_PATH = os.path.join(BASE_DIR,'apps/trade/keys/private_key.txt')
ALIPAY_NOTIFY_URL = "http://39.106.181.61:8000/alipay/return/"
ALIPAY_RETURN_URL = "http://39.106.181.61:8000/alipay/return/"
ALIPAY_DEBUG_URL = "https://openapi.alipaydev.com/gateway.do"
ALIPAY_ONLINE_URL= "https://openapi.alipay.com/gateway.do"

WECHAT = {
        'APPID': 'wx09a82df3fbf9d3a9',                              # 小程序ID
        'APPSECRET': 'a9bf876aaa883cf9af111eeb513eb029',			# 小程序SECRET
        'MCH_ID': '1225312702',                                     # 商户号
        'SPBILL_CREATE_IP': '39.106.181.61',                            # 终端IP
        'NOTIFY_URL': 'http://39.106.181.61:8000/wxpayNotify',          # 通知地址
        'TRADE_TYPE': 'JSAPI',                                      # 交易类型
        'MERCHANT_KEY': 'e10adc3949ba59abbe56e057f20f883e',         # 商户KEY
}