# Generated by Django 3.0.4 on 2020-03-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='用户生日，日期类型', null=True, verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='用户性别 male female', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话号码 最大11位', max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='用户姓名', max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='session_key',
            field=models.CharField(blank=True, help_text='微信的session_key', max_length=30, null=True, verbose_name='微信session_key'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(help_text='短信验证码', max_length=10, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(help_text='电话号码', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
