# Generated by Django 3.0.4 on 2020-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200320_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text='用户昵称', max_length=30, null=True, verbose_name='昵称'),
        ),
    ]
