# Generated by Django 3.0.4 on 2020-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', help_text='用户头像', upload_to='users/avatar/', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
