# Generated by Django 3.0.4 on 2020-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像', null=True, upload_to='users/avatar/', verbose_name='头像'),
        ),
    ]
