# Generated by Django 3.0.4 on 2020-03-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200327_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(blank=True, help_text='微信openid', max_length=30, null=True, verbose_name='微信openid'),
        ),
    ]
