# Generated by Django 3.0.4 on 2020-03-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketerapplication',
            unique_together=set(),
        ),
    ]
