# Generated by Django 2.2.11 on 2020-03-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketerconfigs_marketingrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketerapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketingcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketingrelationship',
            name='config',
        ),
        migrations.RemoveField(
            model_name='marketingrelationship',
            name='parent_marketer',
        ),
        migrations.RemoveField(
            model_name='marketingrelationship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='MarketerApplication',
        ),
        migrations.DeleteModel(
            name='MarketerConfigs',
        ),
        migrations.DeleteModel(
            name='MarketingCode',
        ),
        migrations.DeleteModel(
            name='MarketingRelationship',
        ),
        migrations.DeleteModel(
            name='TeacherApplication',
        ),
    ]
