# Generated by Django 3.0.4 on 2020-04-05 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0006_marketingrelationship_total_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingrelationship',
            name='parent_marketer',
            field=models.ForeignKey(blank=True, help_text='营销上级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_marketer', to=settings.AUTH_USER_MODEL, verbose_name='课程主管'),
        ),
    ]
