# Generated by Django 3.0.4 on 2020-04-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_auto_20200425_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketerconfigs',
            name='level',
            field=models.IntegerField(choices=[(1, '分销等级一'), (2, '分销等级二'), (3, '分销等级三')], default=1, help_text='配置等级', verbose_name='配置等级'),
        ),
    ]
