# Generated by Django 3.0.4 on 2020-03-20 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0006_auto_20200320_1333'),
        ('user_operation', '0002_auto_20200317_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='comments',
            field=models.CharField(help_text='评论内容', max_length=200, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='course',
            field=models.ForeignKey(help_text='课程id', on_delete=django.db.models.deletion.CASCADE, to='goods.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='user',
            field=models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(default='', help_text='详细地址', max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', help_text='城市', max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.CharField(default='', help_text='区域', max_length=100, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', help_text='省份', max_length=100, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='signer_mobile',
            field=models.CharField(default='', help_text='签收人电话', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='signer_name',
            field=models.CharField(default='', help_text='签收人名称', max_length=100, verbose_name='签收人'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(help_text='用户手机', max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='name',
            field=models.CharField(help_text='用户姓名', max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(help_text='用户课程', on_delete=django.db.models.deletion.CASCADE, to='goods.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='user',
            field=models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', help_text='留言主题', max_length=100, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='user',
            field=models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='has_read',
            field=models.BooleanField(default=False, help_text='是否已读', verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(help_text='消息内容', max_length=500, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.IntegerField(default=0, help_text='发给用户的id，0为全部，否则为用户id', verbose_name='接受用户'),
        ),
    ]
