# Generated by Django 3.0.4 on 2020-03-25 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20200325_1735'),
        ('user_operation', '0003_auto_20200320_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(help_text='用户课程', on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='goods.Course', verbose_name='课程'),
        ),
    ]
