# Generated by Django 3.0.4 on 2020-04-02 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0005_auto_20200326_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCashWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_category', models.IntegerField(choices=[(1, '营销佣金取现'), (2, '教师佣金取现')], help_text='取现类型', verbose_name='取现类型')),
                ('apply_status', models.CharField(choices=[('SUCCESS', '申请成功'), ('REJECT', '申请拒绝'), ('APPLYING', '申请中')], default='APPLYING', help_text='申请状态', max_length=30, verbose_name='申请状态')),
                ('amount', models.FloatField(default=0.0, help_text='取现金额', verbose_name='取现金额')),
                ('added_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='增加时间')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, related_name='application_user', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '取现申请',
                'verbose_name_plural': '取现申请',
            },
        ),
    ]
