# Generated by Django 3.0.4 on 2020-04-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0006_usercashwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercashwithdrawal',
            name='withdraw_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待付款')], default='paying', help_text='提取状态', max_length=30, verbose_name='提取状态'),
        ),
    ]
