# Generated by Django 2.2.11 on 2020-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_usercashwithdrawal_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='是否默认地址', verbose_name='是否默认地址'),
        ),
    ]
