# Generated by Django 3.0.4 on 2020-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0008_useraddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercashwithdrawal',
            name='apply_category',
            field=models.IntegerField(choices=[(1, '课程代表佣金取现'), (2, '教师佣金取现')], help_text='取现类型', verbose_name='取现类型'),
        ),
    ]
